# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BatteryShare' do

  pod 'Firebase/Core'
  pod 'React', :path => '../node_modules/react-native'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

end
